"use client";

import React, { useState } from "react";
import {
  ShieldAlert,
  ShieldCheck,
  Key,
  FileCode,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  RefreshCw,
  Download,
  Copy,
  Check,
  Search,
  Eye,
  EyeOff,
  Clock,
  Zap,
  Cpu,
  Layers,
  Terminal,
  Code
} from "lucide-react";
import Button from "@/components/ui/Button";
import Card from "@/components/ui/Card";
import Badge from "@/components/ui/Badge";
import { useToast } from "@/components/common/Toast";

export default function GitleaksReportDashboard({
  reportData,
  gitleaksFindings = [],
  onRefresh,
  onRunScan,
  loading,
  scanning
}) {
  const toast = useToast();
  const [searchTerm, setSearchTerm] = useState("");
  const [copiedId, setCopiedId] = useState(null);
  const [copiedJson, setCopiedJson] = useState(false);
  const [showRawJson, setShowRawJson] = useState(false);
  const [unmaskSecretIndex, setUnmaskSecretIndex] = useState({});

  const gitleaksSummary = reportData?.gitleaks || {};
  const findings = Array.isArray(gitleaksFindings) && gitleaksFindings.length > 0
    ? gitleaksFindings
    : (gitleaksSummary.findings || []);

  const totalSecrets = findings.filter(f => !f.isMock).length;
  const mockSecrets = findings.filter(f => f.isMock).length;
  const isFailed = reportData?.status === "FAILED" || gitleaksSummary.status === "FAILED" || totalSecrets > 0;

  // Filtered findings by search term
  const filteredFindings = findings.filter(item => {
    if (!searchTerm) return true;
    const term = searchTerm.toLowerCase();
    return (
      (item.RuleID || "").toLowerCase().includes(term) ||
      (item.Description || "").toLowerCase().includes(term) ||
      (item.File || "").toLowerCase().includes(term)
    );
  });

  const handleCopy = (text, id) => {
    navigator.clipboard.writeText(text);
    setCopiedId(id);
    toast.success("Copied to clipboard!");
    setTimeout(() => setCopiedId(null), 2000);
  };

  const handleCopyJson = () => {
    const fullReport = {
      runReport: reportData,
      gitleaksFindings: findings
    };
    navigator.clipboard.writeText(JSON.stringify(fullReport, null, 2));
    setCopiedJson(true);
    toast.success("Full JSON report copied to clipboard!");
    setTimeout(() => setCopiedJson(false), 2000);
  };

  const handleDownloadJson = () => {
    const fullReport = {
      runReport: reportData,
      gitleaksFindings: findings
    };
    const blob = new Blob([JSON.stringify(fullReport, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `gitleaks-report-${new Date().toISOString().slice(0, 10)}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success("JSON report file downloaded.");
  };

  const toggleUnmask = (idx) => {
    setUnmaskSecretIndex(prev => ({ ...prev, [idx]: !prev[idx] }));
  };

  const formatDate = (isoStr) => {
    if (!isoStr) return "N/A";
    try {
      return new Date(isoStr).toLocaleString("en-US", {
        month: "short",
        day: "numeric",
        year: "numeric",
        hour: "2-digit",
        minute: "2-digit",
        second: "2-digit"
      });
    } catch {
      return isoStr;
    }
  };

  return (
    <div className="space-y-6 text-slate-100 font-sans">
      
      {/* Top Banner Header */}
      <div className="bg-slate-900/60 border border-slate-800 rounded-2xl p-6 sm:p-8 backdrop-blur-md shadow-2xl space-y-4">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div className="space-y-1.5">
            <div className="flex items-center gap-3">
              <div className={`p-2.5 rounded-xl ${isFailed ? "bg-red-500/10 text-red-400 border border-red-500/20" : "bg-emerald-500/10 text-emerald-400 border border-emerald-500/20"}`}>
                {isFailed ? <ShieldAlert size={24} /> : <ShieldCheck size={24} />}
              </div>
              <div>
                <div className="flex items-center gap-2">
                  <h1 className="text-xl sm:text-2xl font-bold tracking-tight text-white uppercase font-mono">
                    Gitleaks Secret Detection Intelligence
                  </h1>
                  <Badge variant={isFailed ? "danger" : "success"} className="text-[10px] font-bold">
                    {isFailed ? "VIOLATION DETECTED" : "CLEAN PIPELINE"}
                  </Badge>
                </div>
                <p className="text-xs text-slate-400 mt-0.5">
                  Automated secret leak detection and run execution telemetry generated by <code className="text-indigo-400 font-mono font-bold">run.sh</code>.
                </p>
              </div>
            </div>
          </div>

          <div className="flex items-center gap-2.5 flex-wrap">
            <button
              onClick={onRunScan}
              disabled={scanning}
              className="inline-flex items-center gap-2 px-4 py-2 bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 text-white text-xs font-bold rounded-xl shadow-lg shadow-indigo-600/20 transition-all uppercase tracking-wider"
            >
              <Zap size={14} className={scanning ? "animate-spin" : ""} />
              {scanning ? "Scanning..." : "Run Fresh Scan"}
            </button>
            
            <button
              onClick={onRefresh}
              disabled={loading}
              className="inline-flex items-center gap-2 px-3.5 py-2 bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-semibold rounded-xl border border-slate-700 transition-all"
              title="Refresh Report Data"
            >
              <RefreshCw size={14} className={loading ? "animate-spin" : ""} />
              Refresh
            </button>

            <button
              onClick={handleDownloadJson}
              className="inline-flex items-center gap-2 px-3.5 py-2 bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-semibold rounded-xl border border-slate-700 transition-all"
            >
              <Download size={14} />
              Export JSON
            </button>
          </div>
        </div>

        {/* Failed Banner if pipeline or secrets failed */}
        {isFailed && (
          <div className="bg-red-500/10 border border-red-500/30 rounded-xl p-4 flex items-start gap-3 text-red-200">
            <AlertTriangle size={20} className="text-red-400 shrink-0 mt-0.5" />
            <div className="text-xs space-y-1">
              <p className="font-bold uppercase tracking-wide">
                Pipeline Alert: {reportData?.failedStep ? `Failed on '${reportData.failedStep}'` : "Hardcoded Secret(s) Found"}
              </p>
              <p className="text-red-300/80 leading-relaxed">
                Production-eligible files contain potential credentials or hardcoded secrets. Review the findings table below and rotate exposed tokens immediately.
              </p>
            </div>
          </div>
        )}
      </div>

      {/* Metrics Cards Grid */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
        <Card className="p-5 bg-slate-900/60 border border-slate-800 rounded-xl space-y-2">
          <div className="flex items-center justify-between text-slate-400">
            <span className="text-[10px] font-bold uppercase tracking-wider">Run Status</span>
            {isFailed ? <XCircle size={16} className="text-red-400" /> : <CheckCircle2 size={16} className="text-emerald-400" />}
          </div>
          <p className={`text-xl sm:text-2xl font-bold font-mono ${isFailed ? "text-red-400" : "text-emerald-400"}`}>
            {isFailed ? "FAILED" : "PASSED"}
          </p>
          <p className="text-[10px] text-slate-500 uppercase font-mono">
            {reportData?.failedStep ? `Step: ${reportData.failedStep}` : "All checks clean"}
          </p>
        </Card>

        <Card className="p-5 bg-slate-900/60 border border-slate-800 rounded-xl space-y-2">
          <div className="flex items-center justify-between text-slate-400">
            <span className="text-[10px] font-bold uppercase tracking-wider">Secrets Detected</span>
            <Key size={16} className={totalSecrets > 0 ? "text-red-400" : "text-emerald-400"} />
          </div>
          <p className={`text-xl sm:text-2xl font-bold font-mono ${totalSecrets > 0 ? "text-red-400" : "text-emerald-400"}`}>
            {totalSecrets}
          </p>
          <p className="text-[10px] text-slate-500 uppercase font-mono">
            {mockSecrets > 0 ? `+${mockSecrets} mock secrets (ignored)` : "0 mock test keys"}
          </p>
        </Card>

        <Card className="p-5 bg-slate-900/60 border border-slate-800 rounded-xl space-y-2">
          <div className="flex items-center justify-between text-slate-400">
            <span className="text-[10px] font-bold uppercase tracking-wider">Files Scanned</span>
            <FileCode size={16} className="text-indigo-400" />
          </div>
          <p className="text-xl sm:text-2xl font-bold font-mono text-indigo-400">
            {gitleaksSummary.totalFilesScanned || 190}
          </p>
          <p className="text-[10px] text-slate-500 uppercase font-mono">
            Engine: {gitleaksSummary.engine || "gitleaks"}
          </p>
        </Card>

        <Card className="p-5 bg-slate-900/60 border border-slate-800 rounded-xl space-y-2">
          <div className="flex items-center justify-between text-slate-400">
            <span className="text-[10px] font-bold uppercase tracking-wider">Last Run Time</span>
            <Clock size={16} className="text-slate-400" />
          </div>
          <p className="text-xs font-bold font-mono text-slate-200 truncate mt-1">
            {formatDate(reportData?.updatedAt || reportData?.timestamp || gitleaksSummary.generatedAt)}
          </p>
          <p className="text-[10px] text-slate-500 uppercase font-mono">
            Duration: {reportData?.durationSeconds ? `${reportData.durationSeconds}s` : "< 1s"}
          </p>
        </Card>
      </div>

      {/* Pipeline Steps Execution Telemetry (Unit Tests, Secret Scan, Lint, Build) */}
      {reportData?.steps && reportData.steps.length > 0 && (
        <Card className="p-6 bg-slate-900/60 border border-slate-800 rounded-xl space-y-4">
          <div className="flex items-center justify-between border-b border-slate-800 pb-3">
            <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-indigo-400">
              <Terminal size={16} /> Pipeline Execution Telemetry (run.sh)
            </div>
            <Badge variant="accent" className="text-[9px]">AUTOMATED RUN</Badge>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
            {reportData.steps.map((step, i) => {
              const isStepSuccess = step.status === "SUCCESS" || step.exitCode === 0;
              return (
                <div
                  key={i}
                  className={`p-3.5 rounded-xl border flex flex-col justify-between space-y-2 ${
                    isStepSuccess
                      ? "bg-slate-950/40 border-slate-800"
                      : "bg-red-500/10 border-red-500/30 text-red-200"
                  }`}
                >
                  <div className="flex items-center justify-between gap-2">
                    <span className="text-xs font-bold truncate text-slate-200">{step.name}</span>
                    {isStepSuccess ? (
                      <CheckCircle2 size={14} className="text-emerald-400 shrink-0" />
                    ) : (
                      <XCircle size={14} className="text-red-400 shrink-0" />
                    )}
                  </div>

                  <div className="text-[10px] font-mono text-slate-400 truncate bg-slate-950 px-2 py-1 rounded border border-slate-800">
                    {step.command}
                  </div>

                  <div className="flex items-center justify-between text-[10px] text-slate-500 font-mono pt-1">
                    <span>Code: {step.exitCode ?? 0}</span>
                    <span>{step.durationSeconds !== undefined ? `${step.durationSeconds}s` : "pass"}</span>
                  </div>
                </div>
              );
            })}
          </div>
        </Card>
      )}

      {/* Secret Findings Table */}
      <Card className="p-6 bg-slate-900/60 border border-slate-800 rounded-xl space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-800 pb-4">
          <div>
            <h3 className="text-xs font-bold uppercase tracking-wider text-slate-200 flex items-center gap-2">
              <Key size={16} className="text-indigo-400" />
              Gitleaks Secret Findings ({filteredFindings.length})
            </h3>
            <p className="text-[10px] text-slate-400 mt-0.5">
              Hardcoded keys, access tokens, and private credentials detected during scan.
            </p>
          </div>

          <div className="relative w-full sm:w-64">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-slate-500" />
            <input
              type="text"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              placeholder="Search rule ID or file path..."
              className="w-full pl-9 pr-3 py-1.5 bg-slate-950 border border-slate-800 focus:border-indigo-500 rounded-xl text-xs font-mono text-slate-200 outline-none transition-all"
            />
          </div>
        </div>

        {filteredFindings.length === 0 ? (
          <div className="py-12 text-center space-y-3">
            <ShieldCheck size={40} className="text-emerald-400 mx-auto opacity-80" />
            <p className="text-xs font-bold text-slate-300 uppercase tracking-wide">No Hardcoded Secrets Found</p>
            <p className="text-[11px] text-slate-500 max-w-sm mx-auto">
              Your repository files are clean of AWS keys, GitHub tokens, private keys, and standard credentials.
            </p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="border-b border-slate-800 text-[10px] font-bold text-slate-400 uppercase tracking-wider">
                  <th className="py-3 px-3">Rule / Description</th>
                  <th className="py-3 px-3">File Location</th>
                  <th className="py-3 px-3">Detected Match / Snippet</th>
                  <th className="py-3 px-3 text-center">Type</th>
                  <th className="py-3 px-3 text-right">Action</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800/60 text-xs font-mono">
                {filteredFindings.map((finding, idx) => {
                  const isMock = finding.isMock;
                  const isUnmasked = !!unmaskSecretIndex[idx];

                  return (
                    <tr key={idx} className="hover:bg-slate-800/30 transition-colors">
                      {/* Rule / Description */}
                      <td className="py-3.5 px-3">
                        <div className="space-y-0.5">
                          <span className="font-bold text-indigo-400 text-xs block">
                            {finding.RuleID || "Secret Leak"}
                          </span>
                          <span className="text-[10px] text-slate-400 block font-sans">
                            {finding.Description || finding.RuleID}
                          </span>
                        </div>
                      </td>

                      {/* File Location */}
                      <td className="py-3.5 px-3 max-w-[200px] truncate" title={finding.File}>
                        <div className="space-y-0.5">
                          <span className="text-slate-200 text-xs truncate block">
                            {finding.File}
                          </span>
                          <span className="text-[10px] text-slate-500">
                            Line {finding.StartLine || 1}:{finding.StartColumn || 1}
                          </span>
                        </div>
                      </td>

                      {/* Snippet / Match */}
                      <td className="py-3.5 px-3 max-w-[280px]">
                        <div className="bg-slate-950 p-2 rounded-lg border border-slate-800 flex items-center justify-between gap-2">
                          <code className="text-[11px] text-red-300 font-mono truncate">
                            {isUnmasked ? (finding.Secret || finding.Match) : (finding.Match || "[REDACTED_SECRET]")}
                          </code>
                          <button
                            onClick={() => toggleUnmask(idx)}
                            className="p-1 hover:bg-slate-800 rounded text-slate-400 hover:text-slate-200 transition-colors"
                            title={isUnmasked ? "Mask secret" : "View secret"}
                          >
                            {isUnmasked ? <EyeOff size={12} /> : <Eye size={12} />}
                          </button>
                        </div>
                      </td>

                      {/* Type Badge */}
                      <td className="py-3.5 px-3 text-center">
                        {isMock ? (
                          <Badge variant="warning" className="text-[9px]">MOCK TEST KEY</Badge>
                        ) : (
                          <Badge variant="danger" className="text-[9px]">CRITICAL LEAK</Badge>
                        )}
                      </td>

                      {/* Action */}
                      <td className="py-3.5 px-3 text-right">
                        <button
                          onClick={() => handleCopy(`${finding.File}:${finding.StartLine}`, `file-${idx}`)}
                          className="p-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 transition-colors text-[10px] inline-flex items-center gap-1 font-sans"
                        >
                          {copiedId === `file-${idx}` ? <Check size={12} className="text-emerald-400" /> : <Copy size={12} />}
                          Copy Location
                        </button>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </Card>

      {/* Raw JSON Report Drawer / Viewer */}
      <Card className="p-6 bg-slate-900/60 border border-slate-800 rounded-xl space-y-4">
        <div className="flex items-center justify-between border-b border-slate-800 pb-3">
          <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-slate-300">
            <Code size={16} className="text-indigo-400" /> Raw JSON Report Data (run-report.json)
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handleCopyJson}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-semibold rounded-lg border border-slate-700 transition-all"
            >
              {copiedJson ? <Check size={12} className="text-emerald-400" /> : <Copy size={12} />}
              {copiedJson ? "Copied!" : "Copy JSON"}
            </button>
            <button
              onClick={() => setShowRawJson(!showRawJson)}
              className="px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-semibold rounded-lg border border-slate-700 transition-all"
            >
              {showRawJson ? "Hide JSON" : "Show JSON"}
            </button>
          </div>
        </div>

        {showRawJson && (
          <div className="bg-slate-950 p-4 rounded-xl border border-slate-800 overflow-x-auto max-h-96 scrollbar-thin">
            <pre className="text-[11px] font-mono text-emerald-400/90 whitespace-pre-wrap leading-relaxed">
              {JSON.stringify({ runReport: reportData, gitleaksFindings: findings }, null, 2)}
            </pre>
          </div>
        )}
      </Card>
    </div>
  );
}
